version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: ira-redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: ira-chat-api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload